---
title: "audioLatencyTest"
author: "ESM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(zoo)

```

```{r}
df <- read_excel("C:/Users/erik-/Desktop/audioLatencyTest/Book2.xlsx")
df <- df %>% 
  mutate(
    on_diff = led_on - s_on,
    led_off_adj = led_off+1,
    off_diff = led_off_adj - s_off
    )

df <- df %>% 
  select(on_diff, off_diff) %>% 
  pivot_longer(c(on_diff, off_diff), names_to = "cond", values_to = "values")

df %>% 
  ggplot(aes(x = values, fill = cond))+
  geom_bar(position = position_dodge())

df %>% 
  mutate(ms = values * 1000/240) %>% 
  ggplot(aes(y = ms, x = cond, color = cond ))+
  geom_boxplot()
  

df %>% 
  group_by(cond) %>% 
  summarise(
    mean = mean(values),
    sd = sd(values)
  )



```

```{r}
full_path <- "C:/Users/erik-/Desktop/proprioceptive-velocity-control-unity/testData/"
file <- "audtest1|audtest2"
sub_path <- list.files(full_path, recursive = TRUE) %>% 
  str_subset("trial_results") %>% 
  str_subset(file)

path <- paste0(full_path, sub_path)

df <- read_csv(path)

ard <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(arduino_data_location_0)))
track <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(tracker2d_movement_location_0)))

ard <- ard %>% left_join(track %>% select(time, trialID, vibBoth, targetNumber), by = c("time"))

ard %>% filter(frequency < 500)
```


```{r}
turn_on <- ard %>%
  filter(vibBoth == TRUE) %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    micros = micros - first(micros),
    sigamp = if_else(signalAmplitude > 5, 1, 0)) %>% 
  filter(sigamp == 1) %>% 
  summarise(
    first = (first(micros)/1000) - 4 # Audio coroutine is called 4 ms into frame
  ) %>% 
  filter(first < 250 & first > 50)

turn_on %>% 
  summarise(
    mean = mean(first),
    sd = sd(first)
  )
turn_on %>% 
  ggplot(aes(x=first, color = trialID))+
  geom_boxplot()

turn_off <- ard %>% 
  arrange(desc(row_number())) %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    sigamp = if_else(signalAmplitude > 5, 1, 0)
  ) %>% 
  filter(sigamp == 1) %>% 
  mutate(
    micros = abs(micros - first(micros))
  ) %>% 
  filter(vibBoth == FALSE) %>% 
  summarise(
    last = (last(micros)/1000) - 4
  )  %>% 
  filter(last < 250 & last > 50)

turn_off %>% 
  summarise(
    mean = mean(last),
    sd = sd(last)
  )
turn_off %>% 
  ggplot(aes(x=last, color = trialID))+
  geom_boxplot()

```

```{r}
full_path <- "C:/Users/erik-/Desktop/proprioceptive-velocity-control-unity/testData/"
file <- "audtest5"
sub_path <- list.files(full_path, recursive = TRUE) %>% 
  str_subset("trial_results") %>% 
  str_subset(file)

path <- paste0(full_path, sub_path)

df <- read_csv(path)

ard <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(arduino_data_location_0)))
track <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(tracker2d_movement_location_0)))

ard <- ard %>% left_join(track %>% select(time, trialID, vibBoth, targetNumber), by = c("time"))

ard %>% 
  filter(vibBoth == TRUE) %>% 
  group_by(targetNumber) %>% 
  mutate(
    dur = (last(micros) - first(micros)) / 1000
  ) %>% 
  summarise(dur = dur) %>% 
  ggplot(aes(x=dur)) +
  geom_boxplot()

```

```{r}
turn_on_usb <- ard %>% 
  filter(vibBoth == TRUE) %>%
  group_by(targetNumber) %>%
  mutate(
    micros = micros - first(micros)
  ) %>%
  filter(vibrationOn == TRUE) %>% 
  summarise(
    first = first(micros) / 1000
  ) %>% 
  filter(first > 1 & first < 25)

turn_off_usb <- ard %>% 
  arrange(desc(row_number())) %>%
  filter(vibrationOn == TRUE) %>% 
  group_by(targetNumber) %>% 
  filter(vibBoth == FALSE) %>% 
  mutate(
    micros = abs(micros - last(micros))
  ) %>%
  summarise(
    last = last(micros)/1000
  ) %>% 
  filter(last > 1 & last < 25)


turn_on_usb %>% 
  summarise(
    mean = mean(first),
    sd = sd(first)
  )
turn_on_usb %>% 
  ggplot(aes(x=first))+
  geom_boxplot()

turn_on_usb %>% 
  ggplot(aes(x=targetNumber, y = first))+
  geom_point()

##

```

```{r}
turn_on <- ard %>%
  filter(vibrationOn == TRUE) %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    micros = micros - first(micros),
    sigamp = if_else(signalAmplitude > 5, 1, 0)) %>% 
  filter(sigamp == 1) %>% 
  summarise(
    first = (first(micros)/1000) # Audio coroutine is called 4 ms into frame
  ) %>% 
  filter(first < 250 & first > 50)

turn_on %>% 
  summarise(
    mean = mean(first),
    sd = sd(first)
  )
turn_on %>% 
  ggplot(aes(x=first, color = trialID))+
  geom_boxplot()

turn_off <- ard %>% 
  arrange(desc(row_number())) %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    sigamp = if_else(signalAmplitude > 5, 1, 0)
  ) %>% 
  filter(sigamp == 1) %>% 
  mutate(
    micros = abs(micros - first(micros))
  ) %>% 
  filter(vibrationOn == FALSE) %>% 
  summarise(
    last = (last(micros)/1000)
  )  %>% 
  filter(last < 250 & last > 50)

turn_off %>% 
  summarise(
    mean = mean(last),
    sd = sd(last)
  )
turn_off %>% 
  ggplot(aes(x=last, color = trialID))+
  geom_boxplot()
##
turn_on <- ard %>%
  filter(vibBoth == TRUE) %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    micros = micros - first(micros),
    sigamp = if_else(signalAmplitude > 5, 1, 0)) %>% 
  filter(sigamp == 1) %>% 
  summarise(
    first = (first(micros)/1000) # Audio coroutine is called 4 ms into frame
  ) %>% 
  filter(first < 250 & first > 50)

turn_on %>% 
  summarise(
    mean = mean(first),
    sd = sd(first)
  )
turn_on %>% 
  ggplot(aes(x=first, color = trialID))+
  geom_boxplot()

turn_off <- ard %>% 
  arrange(desc(row_number())) %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    sigamp = if_else(signalAmplitude > 5, 1, 0)
  ) %>% 
  filter(sigamp == 1) %>% 
  mutate(
    micros = abs(micros - first(micros))
  ) %>% 
  filter(vibBoth == FALSE) %>% 
  summarise(
    last = (last(micros)/1000)
  )  %>% 
  filter(last < 250 & last > 50)

turn_off %>% 
  summarise(
    mean = mean(last),
    sd = sd(last)
  )
turn_off %>% 
  ggplot(aes(x=last, color = trialID))+
  geom_boxplot()
```
vib test
```{r}
full_path <- "C:/Users/erik-/Desktop/proprioceptive-velocity-control-unity/testData/"
file <- "vibtest4"
sub_path <- list.files(full_path, recursive = TRUE) %>% 
  str_subset("trial_results") %>% 
  str_subset(file)

path <- paste0(full_path, sub_path)

df <- read_csv(path)

ard2 <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(arduino_data_location_0)))
track <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(tracker2d_movement_location_0)))

ard2 <- ard2 %>% left_join(track %>% select(time, trialID, vibLeft, targetNumber, frameStartToAudioStartPre, frameStartToAudioStartPost, frameStartToAudioStopPre, frameStartToAudioStopPost), by = c("time"))

```

```{r}
vibTreshold <- 0.1
azOutlierDect <- 0.05

on_delay <- ard2 %>% 
  group_by(targetNumber) %>% 
  filter(vibLeft == TRUE) %>% 
  mutate(
    time = time - first(time)
  ) %>% 
  mutate(
    sent = time*1000 - frameStartToAudioStartPre,
    delay = sent + stopwatch
  ) %>% 
  mutate(
    az_lag = az - lag(az, default = NULL),
    az_lead = az - lead(az, default = NULL),
    az_outlier = if_else((abs(az_lag) > azOutlierDect) & (abs(az_lead) > azOutlierDect), 1, 0)
  ) %>%
  mutate(
    az2 = az - mean(az[1:15][az_outlier == 0], na.rm = TRUE),
    possibleVib = if_else((abs(az2) > vibTreshold), 1, 0), 
    possibleVibRoll = rollmean(possibleVib, k = 10, fill = NA, align = "left"),
    vibDetected = if_else((possibleVib == 1) & (possibleVibRoll > 0.41), 1, 0) # more than 2 out of next 9 lines should also be detected
  ) %>% 
  filter(vibDetected == 1) %>% 
  summarise(
    delay = first(delay)
  )

on_delay %>% 
  summarise(
    mean = mean(delay),
    sd = sd(delay)
  ) %>% 
  mutate(
    type = "on"
  )



off_delay <- ard2 %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    az_lag = az - lag(az, default = NULL),
    az_lead = az - lead(az, default = NULL),
    az_outlier = if_else((abs(az_lag) > azOutlierDect) & (abs(az_lead) > azOutlierDect), 1, 0)
  ) %>%
  mutate(
    az2 = az - mean(az[-1:-15][az_outlier == 0], na.rm = TRUE),
    possibleVib = if_else((abs(az2) > vibTreshold), 1, 0), 
    possibleVibRoll = rollmean(possibleVib, k = 10, fill = NA, align = "right"),
    vibDetected = if_else((possibleVib == 1) & (possibleVibRoll > 0.41), 1, 0) # more than 2 out of next 9 lines should also be detected
  ) %>% 
  filter(vibDetected == 1) %>%
  filter(vibLeft == FALSE) %>%
  mutate(
    time2 = (time - first(time))*1000
  ) %>% 
  mutate(
    sent = time2 - frameStartToAudioStopPre,
    delay = sent + stopwatch
  ) %>% 
  summarise(
    delay = last(delay)
  )

off_delay %>% 
  summarise(
    mean = mean(delay),
    sd = sd(delay)
  ) %>% 
  mutate(
    type = "on"
  )



off_delay2 <- ard2 %>% 
  arrange(desc(row_number())) %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    az_lag = az - lag(az, default = NULL),
    az_lead = az - lead(az, default = NULL),
    az_outlier = if_else((abs(az_lag) > azOutlierDect) & (abs(az_lead) > azOutlierDect), 1, 0)
  ) %>%
  mutate(
    az2 = az - mean(az[-1:-15][az_outlier == 0], na.rm = TRUE),
    possibleVib = if_else((abs(az2) > vibTreshold), 1, 0), 
    possibleVibRoll = rollmean(possibleVib, k = 10, fill = NA, align = "left"),
    vibDetected = if_else((possibleVib == 1) & (possibleVibRoll > 0.41), 1, 0) # more than 2 out of next 9 lines should also be detected
  ) %>% 
  filter(vibDetected == 1) %>%
  mutate(
    time2 = abs((time - first(time))*1000)
  ) %>% 
  mutate(
    sent = time2 - frameStartToAudioStopPre,
    delay = sent + stopwatch
  ) %>% 
  filter(vibBoth == FALSE) %>% 
  summarise(
    last = (last(micros)/1000)
  )  %>% 
  filter(last < 250 & last > 50)

off_delay2 <- ard %>% 
  arrange(desc(row_number())) %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    sigamp = if_else(signalAmplitude > 5, 1, 0)
  ) %>% 
  filter(sigamp == 1) %>% 
  mutate(
    micros = abs(micros - first(micros))
  ) %>% 
  filter(vibBoth == FALSE) %>% 
  summarise(
    last = (last(micros)/1000)
  )  %>% 
  filter(last < 250 & last > 50)


ard2 %>% 
  group_by(targetNumber) %>% 
  # filter(vibLeft==FALSE) %>% 
  mutate(micros = micros-first(micros)) %>% 
  filter(targetNumber != 0) %>% 
  filter(targetNumber < 10) %>% 
  ggplot(aes(x = micros, y = az, color = factor(targetNumber)))+
  geom_line()+
  facet_wrap(~targetNumber)
```


```{r}
full_path <- "C:/Users/erik-/Desktop/proprioceptive-velocity-control-unity/testData/"
file <- "vibtest4"
sub_path <- list.files(full_path, recursive = TRUE) %>% 
  str_subset("trial_results") %>% 
  str_subset(file)

path <- paste0(full_path, sub_path)

df <- read_csv(path)

ard2 <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(arduino_data_location_0)))
track <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(tracker2d_movement_location_0)))

ard2 <- ard2 %>% left_join(track %>% select(time, trialID, vibLeft, targetNumber, frameStartToAudioStartPre, frameStartToAudioStartPost, frameStartToAudioStopPre, frameStartToAudioStopPost), by = c("time"))

```

```{r}
vibTreshold <- 0.1
audioThresh <- 10
azOutlierDect <- 0.05

on_delay <- ard2 %>% 
  group_by(targetNumber) %>% 
  filter(vibLeft == TRUE) %>% 
  mutate(
    time = time - first(time)
  ) %>% 
  mutate(
    sent = time*1000 - frameStartToAudioStartPre,
    delay = sent + stopwatch
  ) %>% 
  mutate(
    vibDetected = if_else(signalAmplitude > audioThresh, 1, 0)
  ) %>% 
  filter(vibDetected == 1) %>% 
  summarise(
    delay = first(delay)
  ) %>% 
  mutate(
    type = "on"
  )

on_delay %>% 
  summarise(
    mean = mean(delay),
    sd = sd(delay)
  )



off_delay <- ard2 %>% 
  group_by(trialID, targetNumber) %>% 
  mutate(
    vibDetected = if_else(signalAmplitude > audioThresh, 1, 0)
  ) %>% 
  filter(vibDetected == 1) %>%
  filter(vibLeft == FALSE) %>%
  mutate(
    time2 = (time - first(time))*1000
  ) %>% 
  mutate(
    sent = time2 - frameStartToAudioStopPre,
    delay = sent + stopwatch
  ) %>% 
  summarise(
    delay = last(delay)
  ) %>% 
  mutate(
    type = "off"
  )

off_delay %>% 
  summarise(
    mean = mean(delay),
    sd = sd(delay)
  )

delay_by_audio <- on_delay %>% bind_rows(off_delay)
delay_by_audio

delay_by_audio %>% 
  ggplot(aes(x=delay, color = type))+
  geom_boxplot()

```



```{r}
vib_on <- ard2 %>% 
  filter(vibrationOn == TRUE) %>% 
  group_by(targetNumber) %>% 
  mutate(
    micros = micros - first(micros),
    az2 = az - mean(az[0:10]),
    vibDetected = if_else(abs(az2) > 0.1,1,0)
  ) %>% 
  filter(vibDetected == 1) %>% 
  summarise(
    first = first(micros)/1000
  )

vib_on %>% 
  summarise(
    mean = mean(first),
    sd = sd(first)
  )
vib_on %>% 
  ggplot(aes(x=first,))+
  geom_boxplot()

vib_on <- ard2 %>% 
  filter(vibLeft == TRUE) %>% 
  group_by(targetNumber) %>% 
  mutate(
    micros = micros - first(micros),
    az2 = az - mean(az[0:10]),
    vibDetected = if_else(abs(az2) > 0.1,1,0)
  ) %>% 
  filter(vibDetected == 1) %>% 
  summarise(
    first = first(micros)/1000
  )

vib_on %>% 
  summarise(
    mean = mean(first),
    sd = sd(first)
  )
vib_on %>% 
  ggplot(aes(x=first,))+
  geom_boxplot()
```
```{r}
ard2 %>% 
  filter(vibrationOn == TRUE) %>% 
  group_by(targetNumber) %>% 
  mutate(
    micros = micros - first(micros),
    az2 = az - mean(az[0:10]),
    vibDetected = if_else(abs(az2) > 0.05,1,0),
    millis = micros/1000
  ) %>% 
  filter(targetNumber <5) %>% 
  ggplot(aes(y=az2, x = millis))+
  geom_line()+
  facet_wrap(~targetNumber)

ard2 %>% 
  filter(vibrationOn == TRUE) %>% 
  group_by(targetNumber) %>% 
  mutate(
    az2 = az - mean(az[0:10]),
    vibDetected = if_else(abs(az2) > 0.05,1,0),
    micros = micros - first(micros[vibDetected = 1]),
    millis = micros/1000
  ) %>% 
  filter(targetNumber <10) %>%
  ggplot(aes(y=az2, x = millis, color = targetNumber))+
  geom_line()+
  facet_wrap(~targetNumber)


```

```{r}
full_path <- "C:/Users/erik-/Desktop/proprioceptive-velocity-control-unity/testData/"
file <- "dotest6"
sub_path <- list.files(full_path, recursive = TRUE) %>% 
  str_subset("trial_results") %>% 
  str_subset(file)

path <- paste0(full_path, sub_path)

df <- read_csv(path)

ard <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(mpu_data_location_0)))
aud <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(audio_data_location_0)))
track <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(tracker2d_movement_location_0)))

ard <- ard %>% left_join(track %>% select(time, trialID, vibLeft, targetNumber, frameStartToAudioStartPre, frameStartToAudioStopPre), by = c("time")) %>% mutate(signal = az, type = "acc")
aud <- aud %>% left_join(track %>% select(time, trialID, vibLeft, targetNumber, frameStartToAudioStartPre, frameStartToAudioStopPre), by = c("time")) %>% mutate(signal = signalAmplitude, type = "aud")

dat <- bind_rows(ard, aud)


```
```{r}

dat <- dat %>% 
  filter(targetNumber > 0) %>% 
  group_by(type, targetNumber) %>% 
  mutate(
    signal = signal-mean(signal[1:10]),
    signal = signal/max(signal),
    detect = if_else(abs(signal) > .1, TRUE, FALSE))

dat <- dat %>% 
  mutate(
    halfRoundTrip = (((first(time[vibrationOn == 1])*1000) + first(frameOffset[vibrationOn == 1])) - ((first(time[vibLeft == TRUE])*1000)+first(frameStartToAudioStartPre[vibLeft == TRUE])))/2
  ) %>% 
  ungroup() %>% 
  mutate(
    meanHalfRoundTrip = mean(halfRoundTrip[halfRoundTrip > 0], na.rm = TRUE),
    halfRoundTrip = if_else(
      (halfRoundTrip < 0) | is.na(halfRoundTrip), 
      meanHalfRoundTrip, 
      halfRoundTrip
    )
  ) %>% 
  group_by(type, targetNumber)

dat <- dat %>% 
  group_by(type, targetNumber) %>% 
  mutate(delay = ((first(time[detect == TRUE])*1000) + first(frameOffset[detect == TRUE])) - (first(time[vibLeft == TRUE])*1000) + first(frameStartToAudioStartPre[vibLeft == TRUE]) - first(halfRoundTrip))

dat %>% filter(type == "acc") %>% 
  ungroup() %>% 
  summarise(
    mean = mean(delay),
    sd = sd(delay))

dat %>% 
  ggplot(aes(x = delay, color = type))+
  geom_boxplot()

dat %>% 
  filter(type == "acc") %>% 
  ungroup() %>% 
  summarise(
    # mean = mean(first(delay)),
    sd(delay))

dat <- dat %>% 
  ungroup() %>% 
  mutate(
    millis = (micros/1000) - halfRoundTrip,
  ) %>% 
  group_by(type, targetNumber) %>% 
  mutate(
    millis = millis - first(millis)
  )
  

dat %>% 
  mutate(
    signal = if_else(type == "aud", signal+1, signal)
  ) %>% 
  filter(targetNumber == 10) %>% 
  ggplot(aes(x = millis, y = signal, color = type))+
  geom_line()+
  geom_hline(yintercept = c(.05, 1.05))+
  facet_wrap(~targetNumber)

```

```{r}


dat <- dat %>% 
  filter(targetNumber > 0) %>% 
  group_by(type, targetNumber) %>% 
  mutate(
    millisStart = frameStartToAudioStartPre - (first(micros)/1000),
    millisStop = frameStartToAudioStopPre - (first(micros)/1000),
    # micros = (micros-first(micros)),
    millis = (micros-first(micros))/1000,
    signal = signal-mean(signal[1:10]),
    signal = signal/max(signal),
    detect = if_else(abs(signal) > .1, TRUE, FALSE))


dat %>% 
  mutate(
    signal = if_else(type == "aud", signal+1, signal)
  ) %>% 
  ggplot(aes(x = millis, y = signal, color = type))+
  geom_line()+
  facet_wrap(~targetNumber)

dat %>% 
  summarise(
    onset = first(millis[detect == TRUE]))

dat <- dat %>% 
  mutate(
    t0 = (first(time[vibLeft == TRUE])*1000) + first(frameStartToAudioStartPre[vibLeft == TRUE]),
    t1 = first(arduinoRecievedTime[vibrationOn == 1])/1000,
    t2 = first(micros[vibrationOn == 1])/1000,
    t3 = (first(time[vibrationOn == 1])*1000) + first(frameOffset[vibrationOn == 1])
  ) %>% 
  mutate(
    offsetMS = ((t1 - t0)+(t2 - t3))/2,
    FP = t1 -(t0 + offsetMS),
    RP = (t3 + offsetMS)-t2
  ) %>% 
  mutate(
    unityMS = (time*1000) + frameOffset,
    arduinoMS = (micros/1000)+offsetMS 
  )


dat %>% 
  mutate(
    arduinoMS - first(arduinoMS[vibLeft == TRUE])
  ) %>% 
  ggplot(aes(x = arduinoMS, y = signal, color = type))+
  geom_line()

dat %>% 
  summarise(
    first(FP)
  )
  
```


```{r}
full_path <- "C:/Users/erik-/Desktop/proprioceptive-velocity-control-unity/testData/"
file <- "singletest2"
sub_path <- list.files(full_path, recursive = TRUE) %>% 
  str_subset("trial_results") %>% 
  str_subset(file)

path <- paste0(full_path, sub_path)

df <- read_csv(path)

# ard <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(mpu_data_location_0)))
aud <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(audio_data_location_0)))
track <- read_csv(paste0(full_path, df %>% filter(trial_num == 1) %>% pull(tracker2d_movement_location_0)))

# ard <- ard %>% left_join(track %>% select(time, trialID, vibLeft, targetNumber, frameStartToAudioStartPre, frameStartToAudioStopPre), by = c("time")) %>% mutate(signal = az, type = "acc")
dat <- aud %>% left_join(track %>% select(time, trialID, vibLeft, targetNumber, frameStartToAudioStartPre, frameStartToAudioStopPre), by = c("time")) %>% mutate(signal = signalAmplitude, type = "aud")

# dat <- bind_rows(ard, aud)
```









