---
title: "EDA"
author: "ESM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=16, fig.height=8)

library(tidyverse)
library(ggforce)
library(patchwork)
library(ggExtra)

```

```{r}
path <- "../../testData/"

all_files <- list.files(path, recursive = TRUE)
# all_files <- all_files %>% str_subset("erik3|erik4|erik5")
# all_files <- all_files %>% str_subset("erik6")
# all_files <- all_files %>% str_subset("maud1")
# all_files <- all_files %>% str_subset("mark1")
# all_files <- all_files %>% str_subset("mark1|maud1")
# all_files <- all_files %>% str_subset("sim1")
# all_files <- all_files %>% str_subset("sim3")
# all_files <- all_files %>% str_subset("D1.1/mark1")
all_files <- all_files %>% str_subset("D1.1/erik3")
# all_files <- all_files %>% str_subset("D2.1/mark1")

trials <- read_csv(paste0(path, all_files %>% str_subset("trial_results.csv"))) %>%
  filter(calibration == FALSE)

tracking <- read_csv(paste0(path, trials %>% pull(tracker1d_movement_location_0))) %>% 
  # select(-c(truepos.y, vispos.y)) %>% 
  # filter(!trialProgress %in% c("trialSetup")) %>% 
  left_join(trials, by = "trialID")

targetOut <- geom_circle(aes(x0 = 0, y0 = 0.4, r = 0.025), color = NA, fill = "lightgreen", alpha = .125)
targetHome <- geom_circle(aes(x0 = 0, y0 = 0, r = 0.025), color = NA, fill = "lightgreen", alpha = .125)
```
```{r}
plot_endpoints <- trials %>% 
  filter(blockNumber %in% c(1)) %>% 
  ggplot(aes(x = trueInput.x, y = trueInput.z, color = interaction(visualXrotation, controllerVisibleTrialStart)))+
  # targetHome + 
  targetOut + 
  geom_point(size = 3) + 
  stat_ellipse(size = 2) +
  stat_summary(aes(x = trueInput.x, y = trueInput.z, color = interaction(visualXrotation, controllerVisibleTrialStart)), 
               fun = mean, geom = "point", size = 5, shape = 17) + 
  coord_fixed(ratio = 1)

plot_endpoints

plot_endpoints <- trials %>% 
  filter(blockNumber %in% c(2)) %>% 
  ggplot(aes(x = trueInput.x, y = trueInput.z, color = interaction(visualXrotation, controllerVisibleTrialStart)))+
  # targetHome + 
  targetOut + 
  geom_point(size = 3) + 
  stat_ellipse(size = 2) +
  stat_summary(aes(x = trueInput.x, y = trueInput.z, color = interaction(visualXrotation, controllerVisibleTrialStart)), 
               fun = mean, geom = "point", size = 5, shape = 17) + 
  coord_fixed(ratio = 1)

plot_endpoints

tracking %>% 
  filter(blockNumber %in% c(1)) %>% 
  filter(practice == FALSE & calibration == FALSE)
  



```



blockNumber 3
```{r}
plot_endpoints1 <- trials %>% 
  filter(blockNumber == 3) %>% 
  ggplot(aes(x = trueInput.x, y = trueInput.z, color = factor(vibration))) +
  targetOut + 
  geom_point(size = 3) + 
  stat_ellipse(level = 0.95, size = 2) +
  coord_fixed(ratio = 1)+
  coord_fixed(ratio = 1)+ theme(legend.position = "bottom")
plot_endpoints1 %>% 
  ggMarginal(groupColour = TRUE, groupFill = TRUE)


plot_endpoints2 <- trials %>%
  filter(blockNumber == 3) %>%
  ggplot(aes(x = trueInput.x, y = trueInput.z, color = factor(vibration))) +
  targetOut +
  geom_point(size = 3) +
  stat_ellipse(level = 0.95, size = 2) +
  coord_fixed(ratio = 1)+ theme(legend.position = "bottom")

plot_endpoints2 %>%
  ggMarginal(groupColour = TRUE, groupFill = TRUE)




```
blockNumber 4
```{r}

plot_b4_endpoint <- tracking %>% 
  mutate(truepos.z = if_else(targetNumber %% 2 == 1, truepos.z - 0.4, truepos.z),
         targetType = factor(if_else(targetNumber %% 2 == 1, "out", "home"), levels = c("out", "home")),
         offsetTarget = case_when(targetNumber < 5 ~ "preoffset", 
                                  targetNumber %in% c(5,6,7) ~ "offset",
                                  targetNumber > 7 ~ "postoffset")) %>% 
  filter(blockNumber == 4) %>% 
  filter(aButtonDown == TRUE) %>%
  ggplot(aes(x = truepos.x, y = truepos.z, color = factor(offsetTarget))) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  targetHome + 
  geom_point(size = 3) + 
  coord_fixed(ratio = 1)+
  facet_grid(
    cols = vars(visualXOffset),
    rows = vars(targetType)
  )

plot_b4_endpoint
plot_b4_endpoint_dens <- tracking %>% 
  mutate(truepos.z = if_else(targetNumber %% 2 == 1, truepos.z - 0.4, truepos.z),
         targetType = factor(if_else(targetNumber %% 2 == 1, "out", "home"), levels = c("out", "home")),
         offsetTarget = case_when(targetNumber < 5 ~ "preoffset", 
                                  targetNumber %in% c(5,6,7) ~ "offset",
                                  targetNumber > 7 ~ "postoffset")) %>% 
  filter(blockNumber == 4) %>% 
  filter(aButtonDown == TRUE) %>%
  ggplot(aes(x = truepos.x, y = factor(visualXOffset), color = factor(offsetTarget))) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_boxplot(position = position_dodge(width = 0.75), outliers = FALSE)+
  geom_point(position = position_dodge(width = 0.75))+
  facet_grid(
    rows = vars(targetType)
  )  
  
  
  
plot_b4_endpoint_dens
```


```{r}
plot_b4_path <- tracking %>% 
  filter(blockNumber == 1) %>% 
  ggplot(aes(x = truepos.x, y = truepos.z, group = trialID)) +
  targetHome + 
  targetOut + 
  geom_path(size = 1) + 
  coord_fixed(ratio = 1, xlim = c(-.2, .2))+
  facet_grid(
    cols = vars(visualXOffset)
  )
plot_b4_path
```

```{r}
tracking %>% 
  filter(block_num == 3) %>% 
  filter(aButtonDown == TRUE) %>% 
  ggplot(aes(x = angleStartToController, y = vibration))+
  geom_boxplot()

tracking %>%
  group_by(trialID) %>% 
  mutate(endtime = time[aButtonDown == TRUE]) %>% 
  filter(time <= endtime) %>% 
  filter(block_num == 2) %>% 
  ggplot(aes(x = angleStartToPacer, y = angleStartToController, group = trialID, color = vibration))+
  geom_path()+
  geom_abline(intercept = 0, slope = 1, color = "black", linetype = "dashed")+
  geom_vline(xintercept = - 20 + 6.5, color = "black", linetype = "dashed")+
  geom_vline(xintercept = 80, color = "black", linetype = "dashed")+
  geom_hline(yintercept = 80, color = "black", linetype = "dashed")+
  facet_wrap(~vibration)

tracking %>%
  group_by(trialID) %>% 
  mutate(endtime = time[aButtonDown == TRUE]) %>% 
  filter(time <= endtime) %>% 
  filter(block_num == 3) %>% 
  ggplot(aes(x = angleStartToPacer, y = angleStartToController, group = trialID, color = vibration))+
  geom_path()+
  geom_abline(intercept = 0, slope = 1, color = "black", linetype = "dashed")+
  geom_vline(xintercept = - 40 + 6.5, color = "black", linetype = "dashed")+
  geom_vline(xintercept = 80, color = "black", linetype = "dashed")+
  geom_hline(yintercept = 80, color = "black", linetype = "dashed")+
  facet_grid(
    cols = vars(vibration),
    rows = vars(vibrationStartFraction))


tracking %>%
  group_by(trialID) %>% 
  mutate(endtime = time[aButtonDown == TRUE]) %>% 
  filter(trialProgress %in% c("trialStarted")) %>% 
  filter(time <= endtime) %>% 
  filter(block_num == 3) %>% 
  ggplot(aes(x = angleStartToPacer, y = angleStartToController, group = trialID, color = vibration))+
  geom_path()+
  geom_abline(intercept = 0, slope = 1, color = "black", linetype = "dashed")+
  geom_vline(xintercept = - 40 + 6.5, color = "black", linetype = "dashed")+
  geom_vline(xintercept = 80, color = "black", linetype = "dashed")+
  geom_hline(yintercept = 80, color = "black", linetype = "dashed")+
  facet_grid(
    cols = vars(vibration),
    rows = vars(vibrationStartFraction))  
  
tracking %>%
  group_by(trialID) %>% 
  mutate(endtime = time[aButtonDown == TRUE]) %>% 
  filter(time <= endtime) %>% 
  filter(block_num == 3) %>% 
  filter(trialProgress %in% c("trialStarted")) %>% 
  filter(angleStartToController > 0.5) %>% 
  ggplot(aes(x = angleStartToPacer, y = angleStartToController, color = vibration))+
  # geom_path(aes(group = trialID))+
  geom_abline(intercept = 0, slope = 1, color = "black", linetype = "dashed")+
  geom_vline(xintercept = - 40 + 6.5, color = "black", linetype = "dashed")+
  geom_vline(xintercept = 80, color = "black", linetype = "dashed")+
  geom_hline(yintercept = 80, color = "black", linetype = "dashed")+
  geom_smooth(method = "lm")+
  facet_grid(
    rows = vars(vibrationStartFraction))   

```



```{r}
2 * pi * 40 * (10/360)
2 * pi * 15 * (10/360)

```






















